### ISSUE TITLE
Bug in the geoFire library

### ISSUE THREAD

**Issue by Coco0185** [firebase/geofire-js#258]
Hi ,

here is my configuration : with the "npm list" command :

+-- eslint-config-google@0.14.0
+-- eslint@8.31.0
+-- firebase-admin@10.3.0
+-- firebase-functions-test@0.2.3
+-- firebase-functions@3.24.1
+-- firebase@8.0.0
+-- geofire-common@6.0.0
+-- geofire@5.2.0
`-- stripe@11.7.0

I have this error on this js line :

await geoFireApp.set(context.params.pushId, [original.pickup.lat, original.pickup.lng])

the details :

let geoFireRef = admin.database().ref().child('customerRequest');
console.log("geoFireRef: " + geoFireRef);
let geoFireApp = new geofire.GeoFire(geoFireRef);
console.log("geoFireApp: " + geoFireApp);
await geoFireApp.set(context.params.pushId, [original.pickup.lat, original.pickup.lng])

you can find the logs attached
[downloaded-logs-20230131-095956.csv](https://github.com/firebase/geofire-js/files/10544556/downloaded-logs-20230131-095956.csv)

I ve found someone who had the same issue he recommend to downgrade firebase and geofire I've tried (actually the versions in this message are already downgraded) but it doesnt work.

Do you have any idea?

Thank you for your 

### Version info

**Firebase:**

**GeoFire:**

**Other (e.g. Node, browser, operating system) (if applicable):**

**Comment by kaminwong** [comment]
`at /workspace/node_modules/geofire/dist/geofire/index.cjs.js:13322:52
TypeError: Cannot read properties of undefined (reading 'pieceNum_')`

With geofire@6.0.0 I also got an error at this line, after downgrading to firebase@8.0.0 and geofire@5.2.0 it worked fine. I would suggest checking your geofire module and look for this file 'index.cjs.js' because 'pieceNum_' does not exist in geofire@5.2.0, you may still have the newest version installed.

**Comment by AyushBhatia51** [comment]
> `at /workspace/node_modules/geofire/dist/geofire/index.cjs.js:13322:52 TypeError: Cannot read properties of undefined (reading 'pieceNum_')`
> 
> With geofire@6.0.0 I also got an error at this line, after downgrading to firebase@8.0.0 and geofire@5.2.0 it worked fine. I would suggest checking your geofire module and look for this file 'index.cjs.js' because 'pieceNum_' does not exist in geofire@5.2.0, you may still have the newest version installed.

This really helped me i was struck scratching my head for two days, as soon as i downgraded it worked instantly.
